FROM dunglas/frankenphp:1.9.1-php8.4-bookworm

ARG USER=appuser
ARG UID=1000
ARG GID=1000

RUN apt-get update && apt-get install -y --no-install-recommends \
    zip \
    unzip \
    libpq-dev \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    libnss3-tools \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install \
    pdo_pgsql \
    mbstring \
    exif \
    pcntl \
    bcmath \
    gd \
    sockets \
    opcache

# Copy configuration files
COPY docker/php/custom_dev.ini /usr/local/etc/php/conf.d/custom.ini
COPY docker/caddy/Caddyfile.dev /etc/caddy/Caddyfile

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /app

# Create system user to run Composer and Artisan Commands
RUN groupadd -g ${GID} ${USER} && \
    useradd -m -u ${UID} -g ${USER} -d /home/${USER} ${USER} && \
    mkdir -p /home/${USER}/.composer && \
    chown -R ${USER}:${USER} /home/${USER} && \
    chown -R ${USER}:${USER} /app /config/caddy /data/caddy

# Copy dependencies files
COPY --chown=${USER}:${USER} composer.json composer.lock ./

COPY --chown=${USER}:${USER} docker/start.sh /app/docker/start.sh
COPY --chown=${USER}:${USER} . .
RUN chmod +x /app/docker/start.sh

USER $USER

# Run shell file
CMD ["/app/docker/start.sh"]
